### ISSUE TITLE
Document the representation of date-like types

### ISSUE THREAD

**Issue by jakubfijalkowski** [leancodepl/contractsgenerator#60]
We need to set in stone how we represent date-like components:
* `TimeSpan`,
* `DateTime`,
* `DateTimeOffset`,
* `Date`, and
* `Time`.

Having it runtime-dependent makes problems like [this](https://github.com/leancodepl/contractsgenerator-dart/issues/35) hard to solve. Another problem is accuracy - for example, how precise the time in `DateTime` is? .NET/SQL Server support 100 ns accuracy, but both JS and Dart support only 1 ms. We need to cap the precision. 1ms seems like the easiest/least problematic choice. It's not that far from 100ns ( ;) ), and it carries enough data for the most common cases. If someone need anything more precise, they already need to use different mechanisms.

**Comment by shilangyu** [comment]
I don't think it makes a difference but just in case: Dart's time types have a precision of 1us (which is "just" one order of magnitude off 100ns).

Still, 1ms sounds reasonable.

**Comment by Saancreed** [comment]
Some more things to consider:

* PostgreSQL's `timestamp with time zone` type we use for storing `DateTime` .NET type has 1µs resolution.
* ECMAScript's [`Temporal` proposal](https://tc39.es/proposal-temporal/docs/index.html) includes types with precision in nanoseconds.
* NodaTime measures time with a granularity of nanoseconds. Probably not relevant for us as we are (so far) okay with using only BCL types on .NET side of things.

I'd be okay with 1ms _for now_, but I'd also very much want to increase precision to 1µs once Temporal is included in the formal ECMAScript standard.

Besides, whose responsibility will it be to actually ensure that anything more precise will be discarded? Should both server and client trim such values on serialization (or deserialization)?

Finally, while we have already encountered issues because of differences in _resolution_, we haven't had any issues arising from possible differences in _range_ of various `DateTime` types. For example, .NET won't be too happy about having to handle a date with year 29349, which is what an `Temporal.Instant` can represent, or year 275760 which can be happily handled by Dart:

```dart
#!/usr/bin/env dart

import 'dart:io';

void main() {
    print(DateTime.parse("+275760-09-13").toIso8601String());
}
```

At least I hope we can assume that our Postgres database won't give us timestamps with year 294276 unless we somehow insert one ourselves.

**Comment by jakubfijalkowski** [comment]
> Besides, whose responsibility will it be to actually ensure that anything more precise will be discarded? Should both server and client trim such values on serialization (or deserialization)?

Both. We should have "conformance tests" here that each implementation should test against.

> we haven't had any issues arising from possible differences in range of various DateTime types

That's, I think, another topic that we should tackle.

**Comment by shilangyu** [comment]
We could also consider creating a shared test suit for checking correctness of client serialization.
